# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\designs_files\designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 657)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(830, 540))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/about_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget{\n"
"    outline:0px;\n"
"}\n"
"\n"
"")
        MainWindow.setIconSize(QtCore.QSize(512, 512))
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setStyleSheet("QPushButton{\n"
"    border-radius:7px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"}")
        self.mainWidget.setObjectName("mainWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainStackedWidget = QtWidgets.QStackedWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainStackedWidget.sizePolicy().hasHeightForWidth())
        self.mainStackedWidget.setSizePolicy(sizePolicy)
        self.mainStackedWidget.setObjectName("mainStackedWidget")
        self.welcomePage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcomePage.sizePolicy().hasHeightForWidth())
        self.welcomePage.setSizePolicy(sizePolicy)
        self.welcomePage.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:7px;\n"
"    background-color:rgb(61, 80, 89);\n"
"    font: 10pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 10pt \"Verdana\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"    height:25px;\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    border: 1px solid rgb(61, 80, 89);\n"
"    spacing-left:10px;\n"
"}")
        self.welcomePage.setObjectName("welcomePage")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.welcomePage)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.welcomePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(480, 450))
        self.frame.setMaximumSize(QtCore.QSize(480, 450))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(458, 99))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../icons/about_logo.png"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(30, 20, 30, 20)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.createDBButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createDBButton.sizePolicy().hasHeightForWidth())
        self.createDBButton.setSizePolicy(sizePolicy)
        self.createDBButton.setMinimumSize(QtCore.QSize(100, 45))
        self.createDBButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.createDBButton.setIconSize(QtCore.QSize(28, 28))
        self.createDBButton.setObjectName("createDBButton")
        self.verticalLayout_5.addWidget(self.createDBButton)
        self.openDBButton = QtWidgets.QPushButton(self.frame)
        self.openDBButton.setMinimumSize(QtCore.QSize(0, 45))
        self.openDBButton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.openDBButton.setFont(font)
        self.openDBButton.setIconSize(QtCore.QSize(28, 28))
        self.openDBButton.setObjectName("openDBButton")
        self.verticalLayout_5.addWidget(self.openDBButton)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.recentlyOpenedLayout = QtWidgets.QVBoxLayout()
        self.recentlyOpenedLayout.setContentsMargins(30, 10, 30, 0)
        self.recentlyOpenedLayout.setSpacing(5)
        self.recentlyOpenedLayout.setObjectName("recentlyOpenedLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.recentlyOpenedLayout.addWidget(self.label_5)
        self.recentlyOpenedWidget = QtWidgets.QListWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recentlyOpenedWidget.sizePolicy().hasHeightForWidth())
        self.recentlyOpenedWidget.setSizePolicy(sizePolicy)
        self.recentlyOpenedWidget.setObjectName("recentlyOpenedWidget")
        self.recentlyOpenedLayout.addWidget(self.recentlyOpenedWidget)
        self.verticalLayout_6.addLayout(self.recentlyOpenedLayout)
        self.horizontalLayout_3.addWidget(self.frame)
        self.mainStackedWidget.addWidget(self.welcomePage)
        self.openPage = QtWidgets.QWidget()
        self.openPage.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:5px;\n"
"    background-color:rgb(61, 80, 89);\n"
"    font: 10pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 10pt \"Verdana\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"    height:25px;\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    border: 1px solid rgb(61, 80, 89);\n"
"    spacing-left:10px;\n"
"}")
        self.openPage.setObjectName("openPage")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.openPage)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.openPageFrame = QtWidgets.QFrame(self.openPage)
        self.openPageFrame.setMaximumSize(QtCore.QSize(500, 320))
        self.openPageFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.openPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.openPageFrame.setObjectName("openPageFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.openPageFrame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.passwordGroupBox = QtWidgets.QGroupBox(self.openPageFrame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.passwordGroupBox.setFont(font)
        self.passwordGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.passwordGroupBox.setFlat(False)
        self.passwordGroupBox.setObjectName("passwordGroupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.passwordGroupBox)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.passwordGroupBox)
        self.label_14.setStyleSheet("font: 10pt \"Verdana\";")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.passwordEdit_3 = QtWidgets.QLineEdit(self.passwordGroupBox)
        self.passwordEdit_3.setStyleSheet("font: 10pt \"Verdana\";")
        self.passwordEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit_3.setObjectName("passwordEdit_3")
        self.horizontalLayout_6.addWidget(self.passwordEdit_3)
        self.showPasswordButton_3 = QtWidgets.QPushButton(self.passwordGroupBox)
        self.showPasswordButton_3.setStyleSheet("height:25px;\n"
"background:transparent;")
        self.showPasswordButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/hidden.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showPasswordButton_3.setIcon(icon1)
        self.showPasswordButton_3.setObjectName("showPasswordButton_3")
        self.horizontalLayout_6.addWidget(self.showPasswordButton_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_11.addWidget(self.passwordGroupBox)
        self.keyFileGroupBox = QtWidgets.QGroupBox(self.openPageFrame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.keyFileGroupBox.setFont(font)
        self.keyFileGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.keyFileGroupBox.setFlat(False)
        self.keyFileGroupBox.setObjectName("keyFileGroupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.keyFileGroupBox)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.keyFileGroupBox)
        self.label_13.setStyleSheet("font: 10pt \"Verdana\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pathEdit = QtWidgets.QLineEdit(self.keyFileGroupBox)
        self.pathEdit.setStyleSheet("font: 10pt \"Verdana\";")
        self.pathEdit.setInputMask("")
        self.pathEdit.setDragEnabled(True)
        self.pathEdit.setObjectName("pathEdit")
        self.horizontalLayout_5.addWidget(self.pathEdit)
        self.browseButton = QtWidgets.QPushButton(self.keyFileGroupBox)
        self.browseButton.setStyleSheet("height:25px;\n"
"width:100px;")
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_5.addWidget(self.browseButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_11.addWidget(self.keyFileGroupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(280, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(self.openPageFrame)
        self.okButton.setStyleSheet("height:25px;\n"
"width:100px;")
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_4.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.openPageFrame)
        self.cancelButton.setStyleSheet("height:25px;\n"
"width:100px;")
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_4.addWidget(self.cancelButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addWidget(self.openPageFrame)
        self.mainStackedWidget.addWidget(self.openPage)
        self.newPage = QtWidgets.QWidget()
        self.newPage.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:5px;\n"
"    background-color:rgb(61, 80, 89);\n"
"    font: 10pt \"Verdana\";\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 10pt \"Verdana\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"    height:25px;\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    border: 1px solid rgb(61, 80, 89);\n"
"    spacing-left:10px;\n"
"}")
        self.newPage.setObjectName("newPage")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.newPage)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_2 = QtWidgets.QFrame(self.newPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(412, 434))
        self.frame_2.setMaximumSize(QtCore.QSize(412, 500))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.titleGroupBox = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleGroupBox.sizePolicy().hasHeightForWidth())
        self.titleGroupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.titleGroupBox.setFont(font)
        self.titleGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleGroupBox.setFlat(False)
        self.titleGroupBox.setObjectName("titleGroupBox")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.titleGroupBox)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.titleGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setStyleSheet("font: 10pt \"Verdana\";")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_13.addWidget(self.label_16)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.titleEdit_3 = QtWidgets.QLineEdit(self.titleGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleEdit_3.sizePolicy().hasHeightForWidth())
        self.titleEdit_3.setSizePolicy(sizePolicy)
        self.titleEdit_3.setStyleSheet("font: 10pt \"Verdana\";")
        self.titleEdit_3.setObjectName("titleEdit_3")
        self.verticalLayout_14.addWidget(self.titleEdit_3)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.verticalLayout_17.addWidget(self.titleGroupBox)
        self.passwordGroupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordGroupBox_2.sizePolicy().hasHeightForWidth())
        self.passwordGroupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.passwordGroupBox_2.setFont(font)
        self.passwordGroupBox_2.setObjectName("passwordGroupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.passwordGroupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.passwordGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 300))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.passwordEdit_4 = QtWidgets.QLineEdit(self.passwordGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordEdit_4.sizePolicy().hasHeightForWidth())
        self.passwordEdit_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.passwordEdit_4.setFont(font)
        self.passwordEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit_4.setObjectName("passwordEdit_4")
        self.horizontalLayout_8.addWidget(self.passwordEdit_4)
        self.showPasswordButton_4 = QtWidgets.QPushButton(self.passwordGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showPasswordButton_4.sizePolicy().hasHeightForWidth())
        self.showPasswordButton_4.setSizePolicy(sizePolicy)
        self.showPasswordButton_4.setStyleSheet("height:25px;\n"
"background:transparent;")
        self.showPasswordButton_4.setText("")
        self.showPasswordButton_4.setIcon(icon1)
        self.showPasswordButton_4.setObjectName("showPasswordButton_4")
        self.horizontalLayout_8.addWidget(self.showPasswordButton_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.repeatPasswordEdit = QtWidgets.QLineEdit(self.passwordGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repeatPasswordEdit.sizePolicy().hasHeightForWidth())
        self.repeatPasswordEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.repeatPasswordEdit.setFont(font)
        self.repeatPasswordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repeatPasswordEdit.setObjectName("repeatPasswordEdit")
        self.verticalLayout_12.addWidget(self.repeatPasswordEdit)
        self.verticalLayout_10.addLayout(self.verticalLayout_12)
        self.verticalLayout_17.addWidget(self.passwordGroupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_16.addWidget(self.label_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pathEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.pathEdit_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathEdit_2.sizePolicy().hasHeightForWidth())
        self.pathEdit_2.setSizePolicy(sizePolicy)
        self.pathEdit_2.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.pathEdit_2.setFont(font)
        self.pathEdit_2.setObjectName("pathEdit_2")
        self.horizontalLayout_10.addWidget(self.pathEdit_2)
        self.browseButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.browseButton_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton_2.sizePolicy().hasHeightForWidth())
        self.browseButton_2.setSizePolicy(sizePolicy)
        self.browseButton_2.setMaximumSize(QtCore.QSize(16777215, 27))
        self.browseButton_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.browseButton_2.setStyleSheet("height:25px;\n"
"width:100px;")
        self.browseButton_2.setObjectName("browseButton_2")
        self.horizontalLayout_10.addWidget(self.browseButton_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_10)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.verticalLayout_17.addWidget(self.groupBox)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.okButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.okButton_2.setStyleSheet("height:25px;\n"
"width:100px;")
        self.okButton_2.setObjectName("okButton_2")
        self.horizontalLayout_9.addWidget(self.okButton_2)
        self.cancelButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.cancelButton_2.setStyleSheet("height:25px;\n"
"width:100px;")
        self.cancelButton_2.setObjectName("cancelButton_2")
        self.horizontalLayout_9.addWidget(self.cancelButton_2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11.addWidget(self.frame_2)
        self.mainStackedWidget.addWidget(self.newPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupFrame = QtWidgets.QFrame(self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupFrame.sizePolicy().hasHeightForWidth())
        self.groupFrame.setSizePolicy(sizePolicy)
        self.groupFrame.setMaximumSize(QtCore.QSize(120, 16777215))
        self.groupFrame.setStyleSheet("background-color:rgb(61, 80, 89);\n"
"")
        self.groupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.groupFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.groupFrame.setObjectName("groupFrame")
        self.groupWidget = QtWidgets.QListWidget(self.groupFrame)
        self.groupWidget.setGeometry(QtCore.QRect(0, 40, 121, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupWidget.sizePolicy().hasHeightForWidth())
        self.groupWidget.setSizePolicy(sizePolicy)
        self.groupWidget.setMinimumSize(QtCore.QSize(121, 0))
        self.groupWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groupWidget.setStyleSheet("QListWidget{\n"
"    font:75 10pt \"Arial\";    \n"
"    border: none;\n"
"    background: transparent;\n"
"    show-decoration-selected: 0;\n"
"    outline: 0px;\n"
"}\n"
"\n"
"QListWidget::item{\n"
"    color:white;\n"
"    height:25px;\n"
"}\n"
"\n"
"QListWidget::item:hover{\n"
"    background-color:#4a616c;\n"
"\n"
"}\n"
"\n"
"QListWidget::item:selected{\n"
"    border-left: 3px solid white;\n"
"    background-color: rgb(43, 56, 63);\n"
"}\n"
"\n"
"")
        self.groupWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.groupWidget.setBatchSize(100)
        self.groupWidget.setWordWrap(False)
        self.groupWidget.setSelectionRectVisible(False)
        self.groupWidget.setObjectName("groupWidget")
        self.label = QtWidgets.QLabel(self.groupFrame)
        self.label.setGeometry(QtCore.QRect(23, 0, 51, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(51, 31))
        self.label.setStyleSheet("font: 12pt \"Calibri\";\n"
"color:white;\n"
"")
        self.label.setObjectName("label")
        self.addGroupButton = QtWidgets.QPushButton(self.groupFrame)
        self.addGroupButton.setGeometry(QtCore.QRect(72, 7, 21, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addGroupButton.sizePolicy().hasHeightForWidth())
        self.addGroupButton.setSizePolicy(sizePolicy)
        self.addGroupButton.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton::hover{\n"
"    background-color: rgb(86, 113, 126);\n"
"}")
        self.addGroupButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addGroupButton.setIcon(icon2)
        self.addGroupButton.setIconSize(QtCore.QSize(12, 12))
        self.addGroupButton.setObjectName("addGroupButton")
        self.horizontalLayout.addWidget(self.groupFrame)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolFrame = QtWidgets.QFrame(self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolFrame.sizePolicy().hasHeightForWidth())
        self.toolFrame.setSizePolicy(sizePolicy)
        self.toolFrame.setMinimumSize(QtCore.QSize(0, 42))
        self.toolFrame.setMaximumSize(QtCore.QSize(16777215, 42))
        self.toolFrame.setStyleSheet("background-color: rgb(86, 113, 126);")
        self.toolFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolFrame.setObjectName("toolFrame")
        self.searchEdit = QtWidgets.QLineEdit(self.toolFrame)
        self.searchEdit.setGeometry(QtCore.QRect(10, 10, 181, 23))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.searchEdit.setFont(font)
        self.searchEdit.setStyleSheet("QLineEdit{\n"
"    background-color:white;\n"
"    border-radius:3px;\n"
"    spacing-left:5px;\n"
"}")
        self.searchEdit.setClearButtonEnabled(True)
        self.searchEdit.setObjectName("searchEdit")
        self.addButton = QtWidgets.QPushButton(self.toolFrame)
        self.addButton.setGeometry(QtCore.QRect(200, 5, 30, 30))
        self.addButton.setMinimumSize(QtCore.QSize(0, 0))
        self.addButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:15px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.addButton.setText("")
        self.addButton.setIcon(icon2)
        self.addButton.setIconSize(QtCore.QSize(18, 18))
        self.addButton.setFlat(False)
        self.addButton.setObjectName("addButton")
        self.newButton = QtWidgets.QPushButton(self.toolFrame)
        self.newButton.setGeometry(QtCore.QRect(235, 5, 30, 30))
        self.newButton.setMinimumSize(QtCore.QSize(0, 0))
        self.newButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:15px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.newButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newButton.setIcon(icon3)
        self.newButton.setIconSize(QtCore.QSize(18, 18))
        self.newButton.setFlat(False)
        self.newButton.setObjectName("newButton")
        self.openButton = QtWidgets.QPushButton(self.toolFrame)
        self.openButton.setGeometry(QtCore.QRect(270, 5, 30, 30))
        self.openButton.setMinimumSize(QtCore.QSize(0, 0))
        self.openButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:15px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.openButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openButton.setIcon(icon4)
        self.openButton.setIconSize(QtCore.QSize(18, 18))
        self.openButton.setFlat(False)
        self.openButton.setObjectName("openButton")
        self.lockButton = QtWidgets.QPushButton(self.toolFrame)
        self.lockButton.setGeometry(QtCore.QRect(305, 5, 30, 30))
        self.lockButton.setMinimumSize(QtCore.QSize(0, 0))
        self.lockButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:15px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.lockButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lockButton.setIcon(icon5)
        self.lockButton.setIconSize(QtCore.QSize(22, 22))
        self.lockButton.setFlat(False)
        self.lockButton.setObjectName("lockButton")
        self.autotypeButton = QtWidgets.QPushButton(self.toolFrame)
        self.autotypeButton.setGeometry(QtCore.QRect(340, 5, 30, 30))
        self.autotypeButton.setMinimumSize(QtCore.QSize(0, 0))
        self.autotypeButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:15px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.autotypeButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../icons/autotype.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.autotypeButton.setIcon(icon6)
        self.autotypeButton.setIconSize(QtCore.QSize(20, 20))
        self.autotypeButton.setFlat(False)
        self.autotypeButton.setObjectName("autotypeButton")
        self.aboutButton = QtWidgets.QPushButton(self.toolFrame)
        self.aboutButton.setGeometry(QtCore.QRect(375, 5, 30, 30))
        self.aboutButton.setMinimumSize(QtCore.QSize(0, 0))
        self.aboutButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:15px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.aboutButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon7)
        self.aboutButton.setIconSize(QtCore.QSize(20, 20))
        self.aboutButton.setFlat(False)
        self.aboutButton.setObjectName("aboutButton")
        self.verticalLayout_3.addWidget(self.toolFrame)
        self.splitter = QtWidgets.QSplitter(self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(0)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.keyFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyFrame.sizePolicy().hasHeightForWidth())
        self.keyFrame.setSizePolicy(sizePolicy)
        self.keyFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.keyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyFrame.setLineWidth(0)
        self.keyFrame.setObjectName("keyFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.keyFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.keysWidget = QtWidgets.QListWidget(self.keyFrame)
        self.keysWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.keysWidget.sizePolicy().hasHeightForWidth())
        self.keysWidget.setSizePolicy(sizePolicy)
        self.keysWidget.setStyleSheet("QListWidget{\n"
"    border: none;\n"
"    outline:0px;\n"
"    border-top: 1px solid #bdbdbd;\n"
"}\n"
"\n"
"QListWidget::item:selected{\n"
"    background-color:#b2ddfd;\n"
"\n"
"}\n"
"")
        self.keysWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.keysWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.keysWidget.setLineWidth(0)
        self.keysWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.keysWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.keysWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.keysWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.keysWidget.setSelectionRectVisible(True)
        self.keysWidget.setObjectName("keysWidget")
        self.verticalLayout.addWidget(self.keysWidget)
        self.infoFrame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoFrame.sizePolicy().hasHeightForWidth())
        self.infoFrame.setSizePolicy(sizePolicy)
        self.infoFrame.setStyleSheet("QFrame{\n"
"    background-color:white;\n"
"    border-left:1px solid #bdbdbd;\n"
"    border-top: 1px solid #bdbdbd;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-radius:3px;\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"    border: 1px solid grey;\n"
"}\n"
"\n"
"QLineEdit::hover{\n"
"    border: 1px solid grey;\n"
"}")
        self.infoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoFrame.setLineWidth(0)
        self.infoFrame.setObjectName("infoFrame")
        self.stackedInfoWidget = QtWidgets.QStackedWidget(self.infoFrame)
        self.stackedInfoWidget.setGeometry(QtCore.QRect(1, 1, 461, 671))
        self.stackedInfoWidget.setMinimumSize(QtCore.QSize(240, 0))
        self.stackedInfoWidget.setStyleSheet("border:none;")
        self.stackedInfoWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedInfoWidget.setLineWidth(0)
        self.stackedInfoWidget.setObjectName("stackedInfoWidget")
        self.nothingPage = QtWidgets.QWidget()
        self.nothingPage.setObjectName("nothingPage")
        self.nothingLabel = QtWidgets.QLabel(self.nothingPage)
        self.nothingLabel.setEnabled(True)
        self.nothingLabel.setGeometry(QtCore.QRect(0, 0, 451, 671))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.nothingLabel.sizePolicy().hasHeightForWidth())
        self.nothingLabel.setSizePolicy(sizePolicy)
        self.nothingLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.nothingLabel.setFont(font)
        self.nothingLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nothingLabel.setStyleSheet("border:none;\n"
"color:grey;")
        self.nothingLabel.setLineWidth(0)
        self.nothingLabel.setMidLineWidth(0)
        self.nothingLabel.setTextFormat(QtCore.Qt.AutoText)
        self.nothingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nothingLabel.setIndent(-1)
        self.nothingLabel.setOpenExternalLinks(False)
        self.nothingLabel.setObjectName("nothingLabel")
        self.stackedInfoWidget.addWidget(self.nothingPage)
        self.groupPage = QtWidgets.QWidget()
        self.groupPage.setObjectName("groupPage")
        self.notesGroupEdit = QtWidgets.QPlainTextEdit(self.groupPage)
        self.notesGroupEdit.setGeometry(QtCore.QRect(210, 270, 104, 111))
        self.notesGroupEdit.setStyleSheet("QPlainTextEdit{\n"
"    border:none;\n"
"    border-radius:3px;\n"
"    padding-left:10px;\n"
"}\n"
"QPlainTextEdit::focus{\n"
"    border: 1px solid grey;\n"
"}\n"
"\n"
"QPlainTextEdit::hover{\n"
"    border: 1px solid grey;\n"
"}")
        self.notesGroupEdit.setObjectName("notesGroupEdit")
        self.saveGroupButton = QtWidgets.QPushButton(self.groupPage)
        self.saveGroupButton.setGeometry(QtCore.QRect(210, 510, 41, 41))
        self.saveGroupButton.setMinimumSize(QtCore.QSize(0, 0))
        self.saveGroupButton.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:20px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.saveGroupButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveGroupButton.setIcon(icon8)
        self.saveGroupButton.setIconSize(QtCore.QSize(26, 26))
        self.saveGroupButton.setFlat(False)
        self.saveGroupButton.setObjectName("saveGroupButton")
        self.titleGroupEdit = QtWidgets.QLineEdit(self.groupPage)
        self.titleGroupEdit.setGeometry(QtCore.QRect(40, 210, 361, 41))
        self.titleGroupEdit.setStyleSheet("QLineEdit{\n"
"    font: 75 16pt \"Verdana\";\n"
"    border:none;\n"
"}\n"
"")
        self.titleGroupEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.titleGroupEdit.setObjectName("titleGroupEdit")
        self.label_2 = QtWidgets.QLabel(self.groupPage)
        self.label_2.setGeometry(QtCore.QRect(110, 267, 91, 20))
        self.label_2.setStyleSheet("font: 12pt \"Verdana\";\n"
"border:none;")
        self.label_2.setLineWidth(0)
        self.label_2.setObjectName("label_2")
        self.stackedInfoWidget.addWidget(self.groupPage)
        self.entryPage = QtWidgets.QWidget()
        self.entryPage.setObjectName("entryPage")
        self.label_9 = QtWidgets.QLabel(self.entryPage)
        self.label_9.setGeometry(QtCore.QRect(110, 267, 91, 16))
        self.label_9.setStyleSheet("font: 12pt \"Verdana\";\n"
"border:none;")
        self.label_9.setObjectName("label_9")
        self.titleEdit_2 = QtWidgets.QLineEdit(self.entryPage)
        self.titleEdit_2.setGeometry(QtCore.QRect(40, 210, 361, 41))
        self.titleEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.titleEdit_2.setStyleSheet("QLineEdit{\n"
"    font: 75 16pt \"Verdana\";\n"
"    border:none;\n"
"}\n"
"")
        self.titleEdit_2.setText("")
        self.titleEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titleEdit_2.setObjectName("titleEdit_2")
        self.label_10 = QtWidgets.QLabel(self.entryPage)
        self.label_10.setGeometry(QtCore.QRect(110, 327, 47, 13))
        self.label_10.setStyleSheet("font: 12pt \"Verdana\";\n"
"border:none;")
        self.label_10.setObjectName("label_10")
        self.passwordEdit_2 = QtWidgets.QLineEdit(self.entryPage)
        self.passwordEdit_2.setGeometry(QtCore.QRect(210, 297, 131, 20))
        self.passwordEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit_2.setClearButtonEnabled(True)
        self.passwordEdit_2.setObjectName("passwordEdit_2")
        self.linkEdit_2 = QtWidgets.QLineEdit(self.entryPage)
        self.linkEdit_2.setGeometry(QtCore.QRect(210, 327, 131, 20))
        self.linkEdit_2.setClearButtonEnabled(True)
        self.linkEdit_2.setObjectName("linkEdit_2")
        self.usernameEdit_2 = QtWidgets.QLineEdit(self.entryPage)
        self.usernameEdit_2.setGeometry(QtCore.QRect(210, 267, 131, 20))
        self.usernameEdit_2.setClearButtonEnabled(True)
        self.usernameEdit_2.setObjectName("usernameEdit_2")
        self.label_11 = QtWidgets.QLabel(self.entryPage)
        self.label_11.setGeometry(QtCore.QRect(110, 297, 91, 16))
        self.label_11.setStyleSheet("font: 12pt \"Verdana\";\n"
"border:none;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.entryPage)
        self.label_12.setGeometry(QtCore.QRect(110, 357, 61, 16))
        self.label_12.setStyleSheet("font: 12pt \"Verdana\";\n"
"border:none;")
        self.label_12.setObjectName("label_12")
        self.webButton_2 = QtWidgets.QPushButton(self.entryPage)
        self.webButton_2.setGeometry(QtCore.QRect(160, 510, 41, 41))
        self.webButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.webButton_2.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:20px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.webButton_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../icons/web.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webButton_2.setIcon(icon9)
        self.webButton_2.setIconSize(QtCore.QSize(26, 26))
        self.webButton_2.setFlat(False)
        self.webButton_2.setObjectName("webButton_2")
        self.noteEdit_2 = QtWidgets.QPlainTextEdit(self.entryPage)
        self.noteEdit_2.setGeometry(QtCore.QRect(210, 357, 131, 91))
        self.noteEdit_2.setStyleSheet("QPlainTextEdit{\n"
"    border:none;\n"
"    border-radius:3px;\n"
"    padding-left:10px;\n"
"}\n"
"QPlainTextEdit::focus{\n"
"    border: 1px solid grey;\n"
"}\n"
"\n"
"QPlainTextEdit::hover{\n"
"    border: 1px solid grey;\n"
"}")
        self.noteEdit_2.setObjectName("noteEdit_2")
        self.saveNewEntryButton_2 = QtWidgets.QPushButton(self.entryPage)
        self.saveNewEntryButton_2.setGeometry(QtCore.QRect(210, 510, 41, 41))
        self.saveNewEntryButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.saveNewEntryButton_2.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:20px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.saveNewEntryButton_2.setText("")
        self.saveNewEntryButton_2.setIcon(icon8)
        self.saveNewEntryButton_2.setIconSize(QtCore.QSize(26, 26))
        self.saveNewEntryButton_2.setFlat(False)
        self.saveNewEntryButton_2.setObjectName("saveNewEntryButton_2")
        self.showPasswordButton_2 = QtWidgets.QPushButton(self.entryPage)
        self.showPasswordButton_2.setGeometry(QtCore.QRect(345, 300, 20, 16))
        self.showPasswordButton_2.setStyleSheet("")
        self.showPasswordButton_2.setText("")
        self.showPasswordButton_2.setIcon(icon1)
        self.showPasswordButton_2.setIconSize(QtCore.QSize(16, 16))
        self.showPasswordButton_2.setObjectName("showPasswordButton_2")
        self.removeButton_2 = QtWidgets.QPushButton(self.entryPage)
        self.removeButton_2.setGeometry(QtCore.QRect(260, 510, 41, 41))
        self.removeButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.removeButton_2.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:20px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.removeButton_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton_2.setIcon(icon10)
        self.removeButton_2.setIconSize(QtCore.QSize(26, 26))
        self.removeButton_2.setFlat(False)
        self.removeButton_2.setObjectName("removeButton_2")
        self.saveButton_2 = QtWidgets.QPushButton(self.entryPage)
        self.saveButton_2.setGeometry(QtCore.QRect(210, 510, 41, 41))
        self.saveButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.saveButton_2.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: none;\n"
"    border-radius:20px;\n"
"    background-color:rgb(61, 80, 89);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color:#607e8c;\n"
"    \n"
"}")
        self.saveButton_2.setText("")
        self.saveButton_2.setIcon(icon8)
        self.saveButton_2.setIconSize(QtCore.QSize(26, 26))
        self.saveButton_2.setFlat(False)
        self.saveButton_2.setObjectName("saveButton_2")
        self.stackedInfoWidget.addWidget(self.entryPage)
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.mainStackedWidget.addWidget(self.mainPage)
        self.horizontalLayout_2.addWidget(self.mainStackedWidget)
        MainWindow.setCentralWidget(self.mainWidget)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(MainWindow)
        self.mainStackedWidget.setCurrentIndex(0)
        self.stackedInfoWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DPK"))
        self.label_4.setText(_translate("MainWindow", "Welcome to <b>DPK</b>"))
        self.createDBButton.setText(_translate("MainWindow", "Create new database"))
        self.openDBButton.setText(_translate("MainWindow", "Open existing database"))
        self.label_5.setText(_translate("MainWindow", "Recently opened databases"))
        self.passwordGroupBox.setTitle(_translate("MainWindow", "Password"))
        self.label_14.setText(_translate("MainWindow", "Enter the database password.\n"
""))
        self.passwordEdit_3.setPlaceholderText(_translate("MainWindow", "Password..."))
        self.keyFileGroupBox.setTitle(_translate("MainWindow", "Key file"))
        self.label_13.setText(_translate("MainWindow", "If you have key file, use it.\n"
""))
        self.pathEdit.setPlaceholderText(_translate("MainWindow", " Path..."))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.okButton.setText(_translate("MainWindow", "Ok"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.titleGroupBox.setTitle(_translate("MainWindow", "Title"))
        self.label_16.setText(_translate("MainWindow", "Fill in the field with the title of the database.\n"
""))
        self.titleEdit_3.setPlaceholderText(_translate("MainWindow", "Title..."))
        self.passwordGroupBox_2.setTitle(_translate("MainWindow", "Password"))
        self.label_15.setText(_translate("MainWindow", "The password is the main way to protect the database, \n"
"come up with a good password and try not to forget it.\n"
""))
        self.passwordEdit_4.setPlaceholderText(_translate("MainWindow", "Password..."))
        self.repeatPasswordEdit.setPlaceholderText(_translate("MainWindow", "Repeat password..."))
        self.groupBox.setTitle(_translate("MainWindow", "Key file"))
        self.label_17.setText(_translate("MainWindow", "If you want more security, you can use the key file.\n"
""))
        self.pathEdit_2.setPlaceholderText(_translate("MainWindow", "Path..."))
        self.browseButton_2.setText(_translate("MainWindow", "Browse"))
        self.okButton_2.setText(_translate("MainWindow", "Ok"))
        self.cancelButton_2.setText(_translate("MainWindow", "Cancel"))
        self.groupWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select group</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Groups"))
        self.addGroupButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Create new group</p></body></html>"))
        self.searchEdit.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.addButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Create new entry</p></body></html>"))
        self.addButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.newButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Create new database</p></body></html>"))
        self.newButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Add new entry</p></body></html>"))
        self.openButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open database</p></body></html>"))
        self.openButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Add new entry</p></body></html>"))
        self.lockButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Lock and close database</p></body></html>"))
        self.lockButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Add new entry</p></body></html>"))
        self.autotypeButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Autotype username and password</p></body></html>"))
        self.autotypeButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Add new entry</p></body></html>"))
        self.aboutButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>About the program</p></body></html>"))
        self.aboutButton.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Add new entry</p></body></html>"))
        self.nothingLabel.setText(_translate("MainWindow", "Here will be information \n"
"about the account"))
        self.saveGroupButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save new group</p></body></html>"))
        self.titleGroupEdit.setPlaceholderText(_translate("MainWindow", "Title..."))
        self.label_2.setText(_translate("MainWindow", "Notes:"))
        self.label_9.setText(_translate("MainWindow", "Username:"))
        self.titleEdit_2.setPlaceholderText(_translate("MainWindow", "Title..."))
        self.label_10.setText(_translate("MainWindow", "Link:"))
        self.passwordEdit_2.setPlaceholderText(_translate("MainWindow", "Password..."))
        self.linkEdit_2.setPlaceholderText(_translate("MainWindow", "Link..."))
        self.usernameEdit_2.setPlaceholderText(_translate("MainWindow", "Username..."))
        self.label_11.setText(_translate("MainWindow", "Password:"))
        self.label_12.setText(_translate("MainWindow", "Notes:"))
        self.noteEdit_2.setPlaceholderText(_translate("MainWindow", "Notes..."))
        self.saveNewEntryButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save new entry</p></body></html>"))
        self.saveButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save changes</p></body></html>"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
